### ISSUE TITLE
url parsing no longer working

### ISSUE THREAD

**Issue by oemmerson** [jashandeep-sohi/itv#1]
You app has been working flawlessly, (thanks so much for creating it BTW :)) until today.

```
$ itv.py http://www.itv.com/hub/aviva-premiership-highlights/1a7211a0198
```

Gives 'itv.py: error: could not parse video pid from page' error.

**Comment by jashandeep-sohi** [comment]
It seems ITV have done a redesign.
I'll take a look soon and see if this can be fixed (probably this weekend; quite busy)

**Comment by jashandeep-sohi** [comment]
Fixed.
