### ISSUE TITLE
Broken!

### ISSUE THREAD

**Issue by ghost** [jashandeep-sohi/itv#3]
ITV.com have changed something in the last few hours causing this script to fail.
This URL: https://www.itv.com/hub/coronation-street/1a0694a9210
Returns this: itv.py: error: InvalidVodcrid; No match found for production id: https://old-origin-api.itv.com/playlist/itvonline/ITV/1_0694_9210.001

**Comment by jashandeep-sohi** [comment]
Thanks for letting me know. I'll take a look this weekend.

**Comment by jashandeep-sohi** [comment]
Can you pull from master and confirm everything is working as expected now?

**Comment by martinburchell** [comment]
Seems to be working for me. Thanks @jashandeep-sohi for this quick fix to a great script.
